### ISSUE TITLE
爆弾の見た目変更

### ISSUE THREAD

**Issue by C0A21130** [c0a21024b3/ProjExD#10]
爆弾の色が全て同じ色で単調なのでカラフルにするとより面白いと思います
https://github.com/c0a21024b3/ProjExD/blob/33271c959e849c2ad34660db6e10e0b78a59cf73/ex04/dodge_bomb.py#L32

**Comment by c0a21024b3** [comment]
ありがとうございます。2個目以降の爆弾の色を変更しました
