### ISSUE TITLE
コメント追加のお願い

### ISSUE THREAD

**Issue by C0A21130** [c0a21024b3/ProjExD#4]
関数内にある１時的なへ変数にもコメントがあるとより分かりやすいとおもいます。

https://github.com/c0a21024b3/ProjExD/blob/ba418ce96e7c0b358b7c33aecab1f67f0378d6b5/ex02/calc.py#L11

**Comment by c0a21024b3** [comment]
グローバル変数なので最初にコメントはありましたが、確かにわかりづらかったので変数名をcheck_numに変更しました
