### ISSUE TITLE
例外処理の際の処理方法

### ISSUE THREAD

**Issue by C0A21130** [c0a21024b3/ProjExD#6]
例外処理で例外が発生した際に正しいキーボードの入力を求めるようにした方がいいと思いました。

https://github.com/c0a21024b3/ProjExD/blob/2152db1c9c1b8afee9ef70e19d0b064ab5834075/ex03/maze.py#L24

**Comment by c0a21024b3** [comment]
矢印キー以外が押されたときにメッセージボックスが出るよう修正しました。
